### PR TITLE
Add support for activation script again

### PR DESCRIPTION
**Pull request by Gerschtli**
This would be a global flag. Not sure if there would be use cases where this setting would be needed on a per file level, so I skipped that for the sake of simplicity.

Also I am not sure if it really would be worth it to run the copy command only on activation instead of using the service approach. So not sure if there needs to `cpOnService` and `cpOnActivation` instead of just `copies` (https://github.com/jordanisaacs/homeage/issues/9).

Solves https://github.com/jordanisaacs/homeage/issues/7.

### CODE REVIEW

**Comment by Gerschtli** [comment]
Just a sidenote because I forgot again: `options.md` should be auto-generated, otherwise it will always be somehow outdated.. 
(Not sure why you created that file in the first place TBH, because the options are quite readable in the source code.)

**Comment by jordanisaacs** [comment]
Thanks for the PR but I am gonna let it set for a bit as I need to get the activation checks and cleanup stable before adding anymore features right now. Hopefully once those are finished the options of the module and the script considerations should be more stable to make the activation scripts.

All the semi-finalized work is getting merged into the dev branch if you wanna follow along for the time being.

**Comment by jordanisaacs** [comment]
> Just a sidenote because I forgot again: `options.md` should be auto-generated, otherwise it will always be somehow outdated.. (Not sure why you created that file in the first place TBH, because the options are quite readable in the source code.)

I am a fan of having a separate clean document to read the options from. Definitely would be easier to have an auto-generated doc though, I'll look into how to do that.

**Comment by jordanisaacs** [comment]
Sorry for having this sit for a year. lgtm! will release it in v0.1 in the next few days.

**Pull request merged**
