### PR TITLE
replace isRage with parseDrvName function

### PR DESCRIPTION
**Pull request by gvolpe**
Added an `echo "Binary name ${ageBin}"` as well in case we need to troubleshoot.

### CODE REVIEW

**Comment by jordanisaacs** [comment]
Could you move the `echo` command to a line in the `ExecStart` on line 77 and as a list concat for `activationScript` on 58. That way it shows in every systemd unit, but only echoes once for the activation script. Other than that lgtm

**Comment by gvolpe** [comment]
@jordanisaacs I removed the `echo` because I didn't really understand what you meant. I guess you can add it later together with formatting the code to your liking :)

**Comment by jordanisaacs** [comment]
Sounds good, lgtm! thanks for the pr.

Note: the issue with the echo is that `decryptSecret` function generates a script for each secret decryption. Thus putting "echo" there will print it out for every secret. This is fine for the systemd installation because each stdout  is self contained to the service. But for activation script install it would print it out many times unnecessarily.

**Comment by gvolpe** [comment]
Got your point, makes sense 👍🏽 I'm using it as a `systemd` service so that was not an issue :)

**Pull request merged**
